Repository AirDnS/airDnS-back, pull requests merged in 2024-01, with the labels that each got.

#5 Feat : "초기 도메인 entity 구현"
  build.gradle
  src/main/java/com/example/airdns/AirDnSApplication.java
  src/main/java/com/example/airdns/domain/chatting/entity/Chatting.java
  src/main/java/com/example/airdns/domain/chattinguser/entity/ChattingUsers.java
  src/main/java/com/example/airdns/domain/equipment/entity/Equipments.java
  src/main/java/com/example/airdns/domain/equipmentcategory/entity/EquipmentCategories.java
  src/main/java/com/example/airdns/domain/holiday/entity/Holidays.java
  src/main/java/com/example/airdns/domain/image/entity/Images.java
  src/main/java/com/example/airdns/domain/like/entity/Likes.java
  src/main/java/com/example/airdns/domain/payment/entity/Payments.java
  src/main/java/com/example/airdns/domain/reservation/entity/Reservation.java
  src/main/java/com/example/airdns/domain/review/entity/Reviews.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/main/java/com/example/airdns/domain/roomequipment/entity/RoomEquipments.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
  src/main/java/com/example/airdns/domain/user/enums/UserRole.java
  src/main/java/com/example/airdns/global/common/entity/CommonEntity.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#7 Feat : "Global Exception 초기 설정"
  src/main/java/com/example/airdns/global/exception/CustomException.java
  src/main/java/com/example/airdns/global/exception/GlobalExceptionCode.java
Labels: enhancement

#10 Feat : "Controller Advice를 이용한 GlobalExceptionHandler 구현"
  src/main/java/com/example/airdns/global/advice/GlobalExceptionHandler.java
  src/main/java/com/example/airdns/global/common/dto/CommonResponse.java
Labels: enhancement

#12 Fix : "도메인 별 Entity 수정"
  src/main/java/com/example/airdns/domain/chatting/entity/Chatting.java
  src/main/java/com/example/airdns/domain/chattinguser/entity/ChattingUsers.java
  src/main/java/com/example/airdns/domain/equipment/entity/Equipments.java
  src/main/java/com/example/airdns/domain/equipmentcategory/entity/EquipmentCategories.java
  src/main/java/com/example/airdns/domain/holiday/entity/Holidays.java
  src/main/java/com/example/airdns/domain/image/entity/Images.java
  src/main/java/com/example/airdns/domain/like/entity/Likes.java
  src/main/java/com/example/airdns/domain/payment/entity/Payments.java
  src/main/java/com/example/airdns/domain/reservation/entity/Reservation.java
  src/main/java/com/example/airdns/domain/review/entity/Reviews.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/main/java/com/example/airdns/domain/roomequipment/entity/RoomEquipments.java
Labels: enhancement

#15 Feat : “회원 가입 기능 구현”
  build.gradle
  src/main/java/com/example/airdns/domain/user/controller/UserController.java
  src/main/java/com/example/airdns/domain/user/dto/UserDto.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
  src/main/java/com/example/airdns/domain/user/exception/UserCustomException.java
  src/main/java/com/example/airdns/domain/user/exception/UserExceptionCode.java
  src/main/java/com/example/airdns/domain/user/repository/UserRepository.java
  src/main/java/com/example/airdns/domain/user/service/KakaoService.java
  src/main/java/com/example/airdns/global/config/JpaConfig.java
  src/main/java/com/example/airdns/global/config/RestTemplateConfig.java
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
  src/main/java/com/example/airdns/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
  src/main/java/com/example/airdns/global/jwt/UserDetailsImplV1.java
  src/main/java/com/example/airdns/global/jwt/UserDetailsServiceImplV1.java
  src/main/java/com/example/airdns/global/redis/config/RedisConfig.java
  src/main/java/com/example/airdns/global/redis/dao/RedisDao.java
  src/main/java/com/example/airdns/global/redis/dto/TokenDto.java
  src/main/java/com/example/airdns/global/redis/entity/RefreshToken.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: enhancement

#14 좋아요 API 구현
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
  src/main/java/com/example/airdns/domain/like/exception/LikesException.java
  src/main/java/com/example/airdns/domain/like/exception/LikesExceptionCode.java
  src/main/java/com/example/airdns/domain/like/exception/UserNotLikedException.java
  src/main/java/com/example/airdns/domain/like/repository/LikesRepository.java
  src/main/java/com/example/airdns/domain/like/service/LikesService.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
  src/test/java/com/example/airdns/like/LikesControllerTest.java
  src/test/java/com/example/airdns/like/LikesRepositoryTest.java
  src/test/java/com/example/airdns/like/LikesServiceTest.java
Labels: enhancement

#17 Feat : "reservation 예약 생성 구현"
  src/main/java/com/example/airdns/AirDnSApplication.java
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/airdns/domain/reservation/entity/Reservation.java
  src/main/java/com/example/airdns/domain/reservation/exception/ReservationCustomException.java
  src/main/java/com/example/airdns/domain/reservation/exception/ReservationExceptionCode.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepositoryImplV1.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
Labels: enhancement

#18 Feat : "방 API findById 구현"
  .gitignore
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/main/java/com/example/airdns/domain/room/exception/RoomsCustomException.java
  src/main/java/com/example/airdns/domain/room/exception/RoomsExceptionCode.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepository.java
  src/main/java/com/example/airdns/domain/room/service/RoomsService.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/test/java/com/example/airdns/domain/room/repository/RoomsRepositoryTest.java
  src/test/java/com/example/airdns/domain/room/repository/RoomsTestConstant.java
  src/test/java/com/example/airdns/domain/room/service/RoomsServiceImplTest.java
  src/test/java/com/example/airdns/domain/room/service/RoomsServiceTest.java
Labels: enhancement

#19 Feat : "Swagger-UI 구현 및 적용"
  build.gradle
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/airdns/global/config/SwaggerConfig.java
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#20 리뷰 API 구현
  build.gradle
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/review/controller/ReviewsController.java
  src/main/java/com/example/airdns/domain/review/dto/ReviewsRequestDto.java
  src/main/java/com/example/airdns/domain/review/dto/ReviewsResponseDto.java
  src/main/java/com/example/airdns/domain/review/entity/Reviews.java
  src/main/java/com/example/airdns/domain/review/exception/NotFoundReviewsException.java
  src/main/java/com/example/airdns/domain/review/exception/NotModifyReviewException.java
  src/main/java/com/example/airdns/domain/review/exception/NotRemoveReviewException.java
  src/main/java/com/example/airdns/domain/review/exception/ReviewAlreadyExistsException.java
  src/main/java/com/example/airdns/domain/review/exception/ReviewsException.java
  src/main/java/com/example/airdns/domain/review/exception/ReviewsExceptionCode.java
  src/main/java/com/example/airdns/domain/review/repository/ReviewsRepository.java
  src/main/java/com/example/airdns/domain/review/service/ReviewsService.java
  src/main/java/com/example/airdns/domain/review/service/ReviewsServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/main/java/com/example/airdns/global/config/QueryDslConfig.java
  src/test/java/com/example/airdns/like/LikesServiceTest.java
  src/test/java/com/example/airdns/review/ReviewsControllerTest.java
  src/test/java/com/example/airdns/review/ReviewsRepositoryTest.java
  src/test/java/com/example/airdns/review/ReviewsServiceTest.java
Labels: enhancement

#22 좋아요 API 구현 재요청
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
  src/main/java/com/example/airdns/domain/like/exception/UserNotLikedException.java
  src/main/java/com/example/airdns/domain/like/service/LikesService.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
  src/test/java/com/example/airdns/like/LikesControllerTest.java
  src/test/java/com/example/airdns/like/LikesServiceTest.java
Labels: bug

#23 프런트 조회용 Rooms API 추가
  build.gradle
  src/main/java/com/example/airdns/domain/equipment/exception/EquipmentsCustomException.java
  src/main/java/com/example/airdns/domain/equipment/exception/EquipmentsExceptionCode.java
  src/main/java/com/example/airdns/domain/equipment/repository/EquipmentsRepository.java
  src/main/java/com/example/airdns/domain/equipment/service/EquipmentsService.java
  src/main/java/com/example/airdns/domain/equipment/service/EquipmentsServiceImplV1.java
  src/main/java/com/example/airdns/domain/image/exception/ImagesCustomException.java
  src/main/java/com/example/airdns/domain/image/exception/ImagesExceptionCode.java
  src/main/java/com/example/airdns/domain/image/repository/ImagesRepository.java
  src/main/java/com/example/airdns/domain/image/service/ImagesService.java
  src/main/java/com/example/airdns/domain/image/service/ImagesServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/main/java/com/example/airdns/domain/room/exception/RoomsExceptionCode.java
  src/main/java/com/example/airdns/domain/room/service/RoomsService.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/main/java/com/example/airdns/domain/roomequipment/repository/RoomEquipmentsRepository.java
  src/main/java/com/example/airdns/domain/roomequipment/service/RoomEquipmentsService.java
  src/main/java/com/example/airdns/domain/roomequipment/service/RoomEquipmentsServiceImplV1.java
  src/main/java/com/example/airdns/global/awss3/S3FileUtil.java
  src/main/java/com/example/airdns/global/common/dto/CommonResponse.java
  src/main/java/com/example/airdns/global/config/S3Config.java
  src/main/java/com/example/airdns/global/exception/AWSCustomException.java
  src/main/java/com/example/airdns/global/exception/GlobalExceptionCode.java
  src/main/resources/application.yml
  src/test/java/com/example/airdns/AirDnSApplicationTests.java
  src/test/java/com/example/airdns/domain/room/constant/RoomsTestConstant.java
  src/test/java/com/example/airdns/domain/room/repository/RoomsRepositoryTest.java
  src/test/java/com/example/airdns/domain/room/repository/RoomsTestConstant.java
  src/test/java/com/example/airdns/domain/room/service/RoomsServiceImplTest.java
  src/test/java/com/example/airdns/global/awss3/S3FileUtilTest.java
  src/test/resources/uploadTestImg.png
Labels: enhancement

#32 feat: "기본 dateformat"
  src/main/java/com/example/airdns/global/config/JacksonConfig.java
Labels: enhancement

#30 refactor: "Holidays 변경"
  src/main/java/com/example/airdns/domain/restschedule/entity/RestSchedule.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
Labels: enhancement

#21 payment controller 구현
  src/main/java/com/example/airdns/domain/payment/controller/PaymentController.java
Labels: enhancement

#41 Feat: "유저 정보 업데이트 기능 수정 및 닉네임 램덤하게 부여 기능 구현"
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
  src/main/java/com/example/airdns/domain/oauth2/common/OAuth2UserInfo.java
  src/main/java/com/example/airdns/domain/oauth2/common/OAuth2UserPrincipal.java
  src/main/java/com/example/airdns/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/airdns/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/airdns/domain/oauth2/social/KakaoOAuth2UserInfo.java
  src/main/java/com/example/airdns/domain/review/controller/ReviewsController.java
  src/main/java/com/example/airdns/domain/review/service/ReviewsServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/user/controller/UserController.java
  src/main/java/com/example/airdns/domain/user/controller/UsersController.java
  src/main/java/com/example/airdns/domain/user/dto/UserDto.java
  src/main/java/com/example/airdns/domain/user/dto/UsersRequestDto.java
  src/main/java/com/example/airdns/domain/user/dto/UsersResponseDto.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
  src/main/java/com/example/airdns/domain/user/exception/UsersExceptionCode.java
  src/main/java/com/example/airdns/domain/user/service/UsersService.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
  src/main/java/com/example/airdns/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
  src/main/java/com/example/airdns/global/security/UserDetailsImpl.java
  src/main/java/com/example/airdns/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#42 Feat: "로그 아웃 기능 구현"
  src/main/java/com/example/airdns/domain/oauth2/common/OAuth2UserUnlink.java
  src/main/java/com/example/airdns/domain/oauth2/common/OAuth2UserUnlinkManager.java
  src/main/java/com/example/airdns/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/airdns/domain/oauth2/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/example/airdns/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/airdns/domain/oauth2/social/KakaoOAuth2UserUnlink.java
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/global/jwt/JwtAuthorizationFilter.java
Labels: enhancement

#38 CI/CD 구축
  .github/workflows/gradle.yml
  .github/workflows/main.yml
  Dockerfile
  appspec.yml
  deploy.sh
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
Labels: documentation

#46 Feat/reservationAPI
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/airdns/domain/reservation/entity/Reservation.java
  src/main/java/com/example/airdns/domain/reservation/exception/ReservationExceptionCode.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepositoryImplV1.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/restschedule/repository/RestScheduleRepository.java
  src/main/java/com/example/airdns/domain/user/repository/UsersRepository.java
  src/main/java/com/example/airdns/domain/user/service/UsersService.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
Labels: enhancement

#49 CI/CD backend 구현
  .github/workflows/main.yml
  Dockerfile
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
Labels: documentation

#55 feat: "선택 방 조회시 해당 예약 정보를 받아오기"
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
Labels: enhancement

#50 Feat/likes : 룸에 대한 좋아요 구현
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
  src/main/java/com/example/airdns/domain/like/repository/LikesRepository.java
  src/main/java/com/example/airdns/domain/like/service/LikesService.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
  src/test/java/com/example/airdns/like/LikesRepositoryTest.java
  src/test/java/com/example/airdns/like/LikesServiceTest.java
Labels: enhancement

#66 feat: "equipment list 조회 API 추가"
  src/main/java/com/example/airdns/domain/equipment/controller/EquipmentsController.java
  src/main/java/com/example/airdns/domain/equipment/dto/EquipmentsResponseDto.java
  src/main/java/com/example/airdns/domain/equipment/service/EquipmentsService.java
  src/main/java/com/example/airdns/domain/equipment/service/EquipmentsServiceImplV1.java
  src/main/java/com/example/airdns/domain/equipmentcategory/repository/EquipmentCategoriesRepository.java
  src/main/java/com/example/airdns/domain/equipmentcategory/service/EquipmentCategoriesService.java
  src/main/java/com/example/airdns/domain/equipmentcategory/service/EquipmentCategoriesServiceImplV1.java
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
Labels: enhancement

#68 Feat : "유저 단건 조회 및 권한 변경 구현"
  src/main/java/com/example/airdns/domain/user/controller/UsersController.java
  src/main/java/com/example/airdns/domain/user/dto/UsersRequestDto.java
  src/main/java/com/example/airdns/domain/user/dto/UsersResponseDto.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
  src/main/java/com/example/airdns/domain/user/service/UsersService.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
Labels: enhancement

#70 [Reivews] dto, method명 수정
  src/main/java/com/example/airdns/domain/review/controller/ReviewsController.java
  src/main/java/com/example/airdns/domain/review/dto/ReviewsRequestDto.java
  src/main/java/com/example/airdns/domain/review/dto/ReviewsResponseDto.java
  src/main/java/com/example/airdns/domain/review/entity/Reviews.java
  src/main/java/com/example/airdns/domain/review/service/ReviewsService.java
  src/main/java/com/example/airdns/domain/review/service/ReviewsServiceImplV1.java
Labels: enhancement

#71 feat: "방 조회 장비 상세 추가"
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
Labels: enhancement

#73 [Reivews] updateReview 비지니스 로직 수정
  src/main/java/com/example/airdns/domain/review/controller/ReviewsController.java
  src/main/java/com/example/airdns/domain/review/dto/ReviewsResponseDto.java
  src/main/java/com/example/airdns/domain/review/service/ReviewsServiceImplV1.java
Labels: bug

#75 [Likes] Exception 처리가 코드 컨벤션에서 어긋남"
  src/main/java/com/example/airdns/domain/like/exception/LikesCustomException.java
  src/main/java/com/example/airdns/domain/like/exception/LikesException.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
Labels: bug

#83 Fix: "WebSecurityConfig 수정"
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
Labels: bug

#54 결제 요청 back 구현
  build.gradle
  src/main/java/com/example/airdns/domain/payment/controller/PaymentController.java
  src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/example/airdns/domain/payment/entity/Payments.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentService.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
  src/main/java/com/example/airdns/global/common/dto/CommonResponse.java
  src/main/java/com/example/airdns/global/config/PaymentConfig.java
  src/main/resources/application.yml
Labels: enhancement

#85 Feat: "Dto 수정"
  src/main/java/com/example/airdns/domain/payment/dto/PaymentRequestDto.java
Labels: enhancement

#88 Fix: "ReadUserInfoDto 수정"
  src/main/java/com/example/airdns/domain/user/controller/UsersController.java
  src/main/java/com/example/airdns/domain/user/dto/UsersResponseDto.java
  src/main/java/com/example/airdns/domain/user/service/UsersService.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
Labels: improve

#90 Fix: "WebSecurity Cors 경로 수정"
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
Labels: bug

#92 Feat: "CD 구축"
  .github/workflows/cd.yml
  .github/workflows/main.yml
Labels: enhancement

#97 Test: "CD 구동 테스트"
  src/main/java/com/example/airdns/global/jwt/JwtAuthorizationFilter.java
Labels: bug

#94 Test: "CD 테스트"
  Dockerfile
Labels: improve

#98 Feat/fix cicd
  src/main/java/com/example/airdns/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
Labels: bug, enhancement

#99 Feat: "Dto 수정"
  src/main/java/com/example/airdns/domain/payment/entity/Payments.java
Labels: enhancement

#101 Fix: "WebSecurity Config 수정"
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
Labels: bug

#103 Feat: "Infra 구축"
  Dockerfile
  docker-compose.yml
Labels: enhancement

#108 Fix: "Https 요청에 대한 변경"
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
Labels: enhancement

#109 Fix: "LoadBalance 대상 그룹 상태 체크 기능 추가"
  src/main/java/com/example/airdns/global/loadbalance/LoadBalanceController.java
Labels: bug

#125 Fix/login
  src/main/java/com/example/airdns/AirDnSApplication.java
  src/main/java/com/example/airdns/domain/oauth2/dto/ResponseTokenDto.java
  src/main/java/com/example/airdns/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/airdns/domain/oauth2/social/KakaoOAuth2UserInfo.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/main/java/com/example/airdns/domain/user/dto/UsersResponseDto.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
  src/main/java/com/example/airdns/global/config/JpaConfig.java
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
  src/main/java/com/example/airdns/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/example/airdns/global/jwt/JwtCustomExceptionFilter.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
  src/main/java/com/example/airdns/global/redis/RedisConfig.java
Labels: enhancement

#78 Fix : "[Like] Like 관련 API 리팩토링
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
  src/main/java/com/example/airdns/domain/like/exception/LikesExceptionCode.java
  src/main/java/com/example/airdns/domain/like/repository/LikesRepository.java
  src/main/java/com/example/airdns/domain/like/service/LikesService.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
Labels: bug

#106 [payment] reservation 연결
  src/main/java/com/example/airdns/domain/payment/config/AppConfig.java
  src/main/java/com/example/airdns/domain/payment/controller/PaymentController.java
  src/main/java/com/example/airdns/domain/payment/dto/PaymentRequestDto.java
  src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/example/airdns/domain/payment/entity/Payment.java
  src/main/java/com/example/airdns/domain/payment/exception/PaymentCustomException.java
  src/main/java/com/example/airdns/domain/payment/exception/PaymentExceptionCode.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepository.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentService.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
Labels: enhancement

#132 Fix: "예약 예외처리에 대해 수정"
  src/main/java/com/example/airdns/domain/reservation/exception/ReservationExceptionCode.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
Labels: improve

#135 Fix: "Reservation Delete method Patch에서 Delete로 수정"
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
Labels: improve

#134 Fix: "Reservation List ResponseDto 수정"
  build.gradle
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
Labels: bug, improve

#138 Fix: "예약 삭제 대신 취소로 교체"
  src/main/java/com/example/airdns/AirDnSApplication.java
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/airdns/domain/reservation/entity/Reservation.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
Labels: improve

#137 [Payment] 결제조회 메서드 작성
  src/main/java/com/example/airdns/domain/payment/controller/PaymentController.java
  src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/example/airdns/domain/payment/exception/PaymentExceptionCode.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepository.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentService.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
Labels: enhancement

#141 Fix: "HTTPS 설정으로 인한 쿠키 속성 변경 "
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
  src/main/java/com/example/airdns/global/cookie/CookieUtil.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
Labels: bug, improve

#142 Fix: "오타 수정"
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
Labels: bug

#143 Fix: "배포 환경 Cookie 오류 해결"
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
  src/main/java/com/example/airdns/global/cookie/CookieUtil.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
Labels: bug

#145 Fix: "배포 환경 Cookie 오류 해결"
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
Labels: bug

#146 Fix: "Refresh 쿠키 오타 해결"
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
Labels: bug

#148 fix: "파사드 패턴 도입"
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacade.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
  src/main/java/com/example/airdns/domain/restschedule/repository/RestScheduleRepository.java
  src/main/java/com/example/airdns/domain/restschedule/service/RestScheduleService.java
  src/main/java/com/example/airdns/domain/restschedule/service/RestScheduleServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/room/service/RoomsService.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacade.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
Labels: enhancement, improve

#150 Fix: "휴무 버그 수정"
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacade.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
  src/main/java/com/example/airdns/domain/restschedule/repository/RestScheduleRepository.java
  src/main/java/com/example/airdns/domain/restschedule/service/RestScheduleService.java
  src/main/java/com/example/airdns/domain/restschedule/service/RestScheduleServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/exception/RoomsExceptionCode.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
Labels: bug

#128 [Deletion_Management]주요 엔티티 Soft Delete 구현
  build.gradle
  src/main/java/com/example/airdns/AirDnSApplication.java
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeletePaymentsInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeleteReservationsInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeleteRoomsInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeleteUsersInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/exception/DeleteInfoEntityCustomException.java
  src/main/java/com/example/airdns/domain/deleteinfo/exception/DeleteInfoEntityExceptionCode.java
  src/main/java/com/example/airdns/domain/deleteinfo/repository/DeletePaymentsInfoRepository.java
  src/main/java/com/example/airdns/domain/deleteinfo/repository/DeleteReservationInfoRepository.java
  src/main/java/com/example/airdns/domain/deleteinfo/repository/DeleteRoomsInfoRepository.java
  src/main/java/com/example/airdns/domain/deleteinfo/repository/DeleteUsersInfoRepository.java
  src/main/java/com/example/airdns/domain/payment/entity/Payment.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepository.java
  src/main/java/com/example/airdns/domain/reservation/entity/Reservation.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepository.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
  src/main/java/com/example/airdns/domain/user/repository/UsersRepository.java
  src/main/java/com/example/airdns/global/config/WebSecurityConfig.java
  src/main/java/com/example/airdns/global/scheduler/Scheduler.java
Labels: enhancement

#154 room 이슈 정리
  src/main/java/com/example/airdns/domain/image/converter/ImagesConverter.java
  src/main/java/com/example/airdns/domain/image/dto/ImagesResponseDto.java
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsSearchConditionDto.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepository.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQuery.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/room/service/RoomsService.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacade.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
Labels: bug, enhancement

#157 Feat: "회원의 예약 조회 Paging 기능 추가"
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacade.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
Labels: enhancement

#160 Feat: "해당 방에 대한 예약 목록 조회 기능 구현"
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacade.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
Labels: enhancement

#164 Refactor: "예약 성공시 결제를 위한 DTO, Entity 수정"
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/airdns/domain/reservation/entity/Reservation.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacade.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
Labels: enhancement, improve

#166 Refactor/reservation
  src/main/java/com/example/airdns/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/airdns/domain/oauth2/social/KakaoOAuth2UserInfo.java
  src/main/java/com/example/airdns/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacade.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
Labels: improve

#168 Fix : 파라미터 수정
  src/main/java/com/example/airdns/domain/payment/controller/PaymentController.java
  src/main/java/com/example/airdns/domain/payment/dto/PaymentRequestDto.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentService.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
Labels: bug

#171 Feature/room bugfix
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacade.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
  src/main/java/com/example/airdns/domain/roomequipment/service/RoomEquipmentsService.java
  src/main/java/com/example/airdns/domain/roomequipment/service/RoomEquipmentsServiceImplV1.java
Labels: bug, enhancement

#174 Refactor: "유저 정보 DTO 수정"
  src/main/java/com/example/airdns/domain/user/dto/UsersResponseDto.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
Labels: bug, improve

#176 Refactor: "유저 정보 단건 조회 수정"
  src/main/java/com/example/airdns/domain/user/controller/UsersController.java
  src/main/java/com/example/airdns/domain/user/dto/UsersResponseDto.java
  src/main/java/com/example/airdns/domain/user/entity/Users.java
  src/main/java/com/example/airdns/domain/user/service/UsersService.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
Labels: improve

#179 Feat: "프런트 결합 작업 및 버그 수정"
  src/main/java/com/example/airdns/domain/restschedule/repository/RestScheduleRepository.java
  src/main/java/com/example/airdns/domain/restschedule/service/RestScheduleService.java
  src/main/java/com/example/airdns/domain/restschedule/service/RestScheduleServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacade.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
Labels: bug, enhancement, improve

#181 Feat: "Silence Login 기능 추가"
  src/main/java/com/example/airdns/domain/user/controller/UsersController.java
  src/main/java/com/example/airdns/domain/user/service/UsersService.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
  src/main/java/com/example/airdns/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/example/airdns/global/jwt/JwtUtil.java
Labels: enhancement

#184 Docs: "Readme 서비스 기획 추가"
  README.md
Labels: enhancement

#182 Refactor : 스케줄러 리펙토링
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeletePaymentsInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeleteReservationsInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeleteRoomsInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/entity/DeleteUsersInfo.java
  src/main/java/com/example/airdns/domain/deleteinfo/exception/DeleteInfoEntityCustomException.java
  src/main/java/com/example/airdns/domain/deleteinfo/exception/DeleteInfoEntityExceptionCode.java
  src/main/java/com/example/airdns/domain/deleteinfo/service/DeleteInfoService.java
  src/main/java/com/example/airdns/domain/deleteinfo/service/DeleteInfoServiceImpl.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepository.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepositoryQuery.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentService.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepositoryQuery.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationService.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacade.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepository.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQuery.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/room/service/RoomsService.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacade.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
  src/main/java/com/example/airdns/domain/user/repository/UsersRepository.java
  src/main/java/com/example/airdns/domain/user/repository/UsersRepositoryQuery.java
  src/main/java/com/example/airdns/domain/user/repository/UsersRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/user/service/UsersService.java
  src/main/java/com/example/airdns/domain/user/service/UsersServiceImplV1.java
  src/main/java/com/example/airdns/global/scheduler/Scheduler.java
Labels: bug, enhancement, improve
