Repository AirDnS/airDnS-back, pull requests merged in 2024-02, with the labels that each got.

#190 Refactor: "룸 출력을 리스트로 변경"
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsSearchConditionDto.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQuery.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/room/service/RoomsService.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacade.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
  src/main/java/com/example/airdns/global/config/QueryDslConfig.java
Labels: improve

#186 Test : 전체 좋아요 조회에서 방에 대한 좋아요 변경으로 인한 테스트 코드 수정
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/repository/LikesRepository.java
  src/main/java/com/example/airdns/domain/like/service/LikesService.java
  src/test/java/com/example/airdns/like/LikesControllerTest.java
  src/test/java/com/example/airdns/like/LikesRepositoryTest.java
  src/test/java/com/example/airdns/like/LikesServiceTest.java
Labels: enhancement

#191 Feat: "동시성 문제 해결"
  build.gradle
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
  src/test/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1Test.java
Labels: enhancement

#194 Test : Review 단건 조회에서 룸에 대한 ReviewList 변경으로 인한 테스트 코드 수정
  src/main/java/com/example/airdns/domain/review/exception/ReviewsExceptionCode.java
  src/main/java/com/example/airdns/domain/review/service/ReviewsServiceImplV1.java
  src/test/java/com/example/airdns/review/ReviewsControllerTest.java
  src/test/java/com/example/airdns/review/ReviewsRepositoryTest.java
  src/test/java/com/example/airdns/review/ReviewsServiceTest.java
Labels: bug, improve

#195 Refactor : Scheduler 쿼리 최적화
  src/main/java/com/example/airdns/domain/deleteinfo/service/DeleteInfoServiceImpl.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepositoryQuery.java
  src/main/java/com/example/airdns/domain/reservation/repository/ReservationRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQuery.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/main/java/com/example/airdns/global/scheduler/Scheduler.java
Labels: improve

#201 Feat: "방에 대한 좌표 검색 추가"
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsSearchConditionDto.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/global/address/AddressUtil.java
Labels: enhancement

#197 Fix : 방에 대한 유저 액션 수정에 대한 변경작업 및 Swagger 보안 작업
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
  src/test/java/com/example/airdns/like/LikesControllerTest.java
  src/test/java/com/example/airdns/like/LikesServiceTest.java
Labels: bug

#205 Feature/locationsearch
  src/main/java/com/example/airdns/domain/image/repository/ImagesRepository.java
  src/main/java/com/example/airdns/domain/image/repository/ImagesRepositoryQuery.java
  src/main/java/com/example/airdns/domain/image/repository/ImagesRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/image/service/ImagesService.java
  src/main/java/com/example/airdns/domain/image/service/ImagesServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
  src/main/java/com/example/airdns/global/address/AddressUtil.java
Labels: bug, enhancement

#207 Test : 유저 테스트 코드 작성
  src/main/java/com/example/airdns/domain/user/controller/UsersController.java
  src/test/java/com/example/airdns/user/UsersControllerTest.java
  src/test/java/com/example/airdns/user/UsersRepositoryTest.java
  src/test/java/com/example/airdns/user/UsersServiceTest.java
Labels: improve

#211 Test: "swagger 경로 변경 테스트 "
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
Labels: bug, documentation

#215 Feat: "거리 확장 검색 추가"
  src/main/java/com/example/airdns/domain/room/controller/RoomsController.java
  src/main/java/com/example/airdns/domain/room/converter/RoomsConverter.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsRequestDto.java
  src/main/java/com/example/airdns/domain/room/dto/RoomsResponseDto.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQuery.java
  src/main/java/com/example/airdns/domain/room/repository/RoomsRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/room/service/RoomsService.java
  src/main/java/com/example/airdns/domain/room/service/RoomsServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacade.java
  src/main/java/com/example/airdns/domain/room/servicefacade/RoomsServiceFacadeImplV1.java
Labels: enhancement

#217 Feat: "배포 환경 로깅 작업"
  .github/workflows/cd.yml
  .gitignore
  src/main/java/com/example/airdns/domain/reservation/exception/ReservationExceptionCode.java
  src/main/java/com/example/airdns/domain/reservation/servicefacade/ReservationServiceFacadeImplV1.java
  src/main/java/com/example/airdns/global/advice/GlobalExceptionHandler.java
  src/main/java/com/example/airdns/global/jwt/JwtCustomExceptionFilter.java
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-spring.xml
Labels: documentation, enhancement

#216 Refactor: "누락된 swagger 적용"
  src/main/java/com/example/airdns/domain/payment/dto/PaymentRequestDto.java
  src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
Labels: improve

#222 Refactor: "누락된 Swagger 작업"
  src/main/java/com/example/airdns/domain/reservation/dto/ReservationResponseDto.java
Labels: documentation, improve

#220 Refactor : 누락된 Swagger 작업
  src/main/java/com/example/airdns/domain/review/controller/ReviewsController.java
Labels: improve

#218 Refactor : 방에 대한 유저 액션 수정에 대한 변경작업
  src/main/java/com/example/airdns/domain/like/controller/LikesController.java
  src/main/java/com/example/airdns/domain/like/dto/LikesResponseDto.java
  src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
  src/main/java/com/example/airdns/domain/room/entity/Rooms.java
  src/test/java/com/example/airdns/like/LikesControllerTest.java
Labels: enhancement, improve

#224 Test: "payment 테스트 코드 작성"
  src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
  src/test/java/com/example/airdns/domain/payment/PaymentServiceImplTest.java
Labels: improve

#225 Test/reservation test
  src/test/java/com/example/airdns/domain/reservation/constant/CommonTest.java
  src/test/java/com/example/airdns/domain/reservation/constant/ReservationTest.java
  src/test/java/com/example/airdns/domain/reservation/service/ReservationConcurrencyTest.java
  src/test/java/com/example/airdns/domain/reservation/service/ReservationServiceImplV1Test.java
Labels: enhancement, improve

#227 Test: "Payment Service 테스트 코드 작성"
  src/test/java/com/example/airdns/domain/payment/PaymentServiceImplTest.java
Labels: improve

#229 Docs: "기술적 의사 결정 추가"
  README.md
Labels: documentation

#230 Docs: "Directory 구조 접기로 변경"
  README.md
Labels: documentation

#232 Refactor: "불필요한 어노테이션 제거"
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepository.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepositoryQuery.java
  src/main/java/com/example/airdns/domain/payment/repository/PaymentRepositoryQueryImpl.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentService.java
  src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
Labels: improve
